"""
Sympl Solutions Proposal RAG — Playbook Architecture Layer

Contains modular domain playbooks, base Sympl writing style standards,
and dynamic playbook selection registry.
"""

from .base_style import (
    BASE_STYLE_SYSTEM_PERSONA,
    BASE_STYLE_SYSTEM_RULES,
    BASE_STYLE_USER_HEADER,
    BASE_STYLE_USER_INSTRUCTIONS_LINES,
    BASE_STYLE_DOMAIN_NEUTRAL_PERSONA_TEMPLATE,
    BASE_STYLE_DOMAIN_NEUTRAL_RULES,
    BASE_STYLE_DOMAIN_NEUTRAL_USER_HEADER_TEMPLATE,
    BASE_STYLE_DOMAIN_NEUTRAL_USER_INSTRUCTIONS_LINES,
    FORBIDDEN_PHRASES
)
from .accounting_playbook import (
    ACCOUNTING_OPERATIONAL_PLAYBOOK_SYSTEM,
    ACCOUNTING_OPERATIONAL_PLAYBOOK_USER_LINES
)
from .website_playbook import (
    WEBSITE_OPERATIONAL_PLAYBOOK_SYSTEM,
    WEBSITE_OPERATIONAL_PLAYBOOK_USER_LINES
)
from .data_playbook import (
    DATA_OPERATIONAL_PLAYBOOK_SYSTEM,
    DATA_OPERATIONAL_PLAYBOOK_USER_LINES
)
from .finance_transformation_playbook import (
    FINANCE_TRANSFORMATION_PLAYBOOK_SYSTEM,
    FINANCE_TRANSFORMATION_PLAYBOOK_USER_LINES
)
from .general_consulting_playbook import (
    GENERAL_CONSULTING_PLAYBOOK_SYSTEM,
    GENERAL_CONSULTING_PLAYBOOK_USER_LINES
)
from .registry import (
    PlaybookRegistry,
    PlaybookAuditLog,
    PlaybookResolution
)

__all__ = [
    "BASE_STYLE_SYSTEM_PERSONA",
    "BASE_STYLE_SYSTEM_RULES",
    "BASE_STYLE_USER_HEADER",
    "BASE_STYLE_USER_INSTRUCTIONS_LINES",
    "FORBIDDEN_PHRASES",
    "ACCOUNTING_OPERATIONAL_PLAYBOOK_SYSTEM",
    "ACCOUNTING_OPERATIONAL_PLAYBOOK_USER_LINES",
    "WEBSITE_OPERATIONAL_PLAYBOOK_SYSTEM",
    "WEBSITE_OPERATIONAL_PLAYBOOK_USER_LINES",
    "DATA_OPERATIONAL_PLAYBOOK_SYSTEM",
    "DATA_OPERATIONAL_PLAYBOOK_USER_LINES",
    "FINANCE_TRANSFORMATION_PLAYBOOK_SYSTEM",
    "FINANCE_TRANSFORMATION_PLAYBOOK_USER_LINES",
    "GENERAL_CONSULTING_PLAYBOOK_SYSTEM",
    "GENERAL_CONSULTING_PLAYBOOK_USER_LINES",
    "PlaybookRegistry",
    "PlaybookAuditLog",
    "PlaybookResolution"
]
